image: node:8.6.0

stages:
  - codestyle
  - deploy

codestyle:js:
  image: node:9.11.1
  stage: codestyle
  script:
    - npm install
    - npm run standard
    - npm run build
    - cat public/dist/element.bundle.js | grep "Cannot find module" && exit 1
    - if [ $? -eq 0 ]; then echo "good"; exit 0; else echo "fail"; exit 1; fi
  tags:
    - docker

codestyle:php:
  image: wpbakery/phpcs
  stage: codestyle
  script:
    - php ci/phpcs.phar --standard=ci/ruleset.xml imageGalleryWithZoom/
  tags:
    - docker

deploying:
  image: node:8.6.0
  stage: deploy
  script:
    - "ELEMENT_TITLE=`node -e \"var manifest = require('./manifest.json');console.log(encodeURIComponent(manifest.elements[Object.keys(manifest.elements)[0]].settings.name));\"`"
    - "ELEMENT_TAG=`node -e \"var manifest = require('./manifest.json');console.log(Object.keys(manifest.elements)[0]);\"`"
    - "echo \"$CI_HUB_GROUP_TEST_DOMAIN/api/inner/bundle/create?key=$CI_HUB_GROUP_ELEMENTS_BUILD_KEY&bundle=element/$ELEMENT_TAG&version=latest&name=$ELEMENT_TITLE\""
    - "curl -X GET -H 'Content-type: application/json' \"$CI_HUB_GROUP_TEST_DOMAIN/api/inner/bundle/create?key=$CI_HUB_GROUP_ELEMENTS_BUILD_KEY&bundle=element/$ELEMENT_TAG&version=latest&name=$ELEMENT_TITLE\""
  tags:
    - docker
